version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bumpkin
    main: ./cmd/bumpkin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/benny123tw/bumpkin/internal/cli.AppVersion={{.Version}}
      - -X github.com/benny123tw/bumpkin/internal/cli.BuildDate={{.Date}}
      - -X github.com/benny123tw/bumpkin/internal/cli.GitCommit={{.FullCommit}}
    binary: >-
      {{ .ProjectName }}-
      {{- if .IsSnapshot }}{{ .Branch }}-
      {{- else }}{{- .Version }}-{{ end }}
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "amd64_v1" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
    no_unique_dist_dir: true

archives:
  - formats: ["binary"]
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}"

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "Refactor"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 4
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 5
    - title: Others
      order: 999

release:
  github:
    owner: benny123tw
    name: bumpkin
  draft: false
  prerelease: auto
